### PR TITLE
Cameron wants Andre's awesome code

### PR DESCRIPTION
**Pull request by xmypizzax**

### CODE REVIEW

**Comment by xmypizzax** [comment]
Why? :(

**Comment by Camnewb** [comment]
I still need Andres (not awesome) code

**Comment by EricRabil** [comment]
@xmypizzax @Camnewb Cameron's changes were the last changes on our per-person branch. Andre's code was already merged into master. All of our code is on the master and develop branch now, including this code. Your stuff is not gone.

**Comment by xmypizzax** [comment]
Oh, okay!

**Pull request closed without merging**
